POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhbWRlbiIsImlkIjoiNWY3ZTczMTU2MGE3NGI1MTk1Njg5NzU1IiwiaWF0IjoxNjA1MTQ0MzA0fQ.bxo2j4gqC_hNoRBtXd9aIe-GbjukO_yYMIqUedeUcu8

{
    "title": "test",
    "author": "test",
    "url": "ddfewfwewfeg.gg",
    "likes": 122
}