name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull-request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn eslint
      - name: build
        run: yarn build
      - name: test
        env:
          INVITE_KEY: ${{ secrets.INVITE_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        run: yarn test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          INVITE_KEY: ${{ secrets.INVITE_KEY }}
          CYPRESS_INVITE_KEY: ${{ secrets.INVITE_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        with:
          env: true
          command: yarn test:e2e
          start: yarn start:cypress
          wait-on: http://localhost:3001
      - name: deploy on heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: morning-citadel-33926
          heroku_email: c@camdenmecklem.com
          healthcheck: https://morning-citadel-33926.herokuapp.com/health
          checkstring: ok
          rollbackonhealthcheckfailed: true